server:
  port: 8082

spring:
  application:
    name: spot-study

  datasource:
    url: jdbc:mysql://localhost:3306/spot_study
    username: root
    password: 5167
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
